### ISSUE TITLE
Will this work for Indian cars?

### ISSUE THREAD

**Issue by jcopps** [sujaybhowmick/OpenAlprDroidApp#8]
I noticed there is an arg sent as US/EU. 
What are the tweaks to be made to work for Indian cars. 

Tried for the following:
http://www.team-bhp.com/forum/attachments/indian-car-scene/500833d1297572797-high-security-registration-plates-hsrp-india-imag0127.jpg
Any reason it predicted wrong.

**Comment by sujaybhowmick** [comment]
No, it will not work for Indian Number plates. However, you train the model for Indian plates. You will have to provide positive and negative training images of number plates to train the model. The detailed steps are provided in the train-detector project https://github.com/sujaybhowmick/train-detector  on how to train the model.
